app = 'qrcodesequenciais'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = "python manage.py runserver 0.0.0.0:8000"

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'